# Generated by Django 5.2 on 2025-06-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=40, verbose_name='Votre nom :')),
                ('client_phone', models.CharField(max_length=20, verbose_name='Votre numéro téléphone :')),
                ('client_email', models.CharField(max_length=50, verbose_name='Votre email :')),
                ('message_object', models.CharField(choices=[('simple', 'Simple prise de contact 🤝'), ('date', 'Prise de rendez-vous 📅')], default='web', max_length=6, verbose_name='Objet du contact :')),
                ('message', models.TextField(verbose_name='Votre message :')),
                ('date_reason', models.CharField(choices=[('web', 'Création de site web | application web 🌐'), ('mobile', "Création d'application mobile 📱"), ('hosting', "Mise en ligne d'une application web | mobile 🧱")], default='simple', max_length=7, verbose_name='Raison du prise de rendez-vous :')),
                ('register_date', models.DateField(auto_now_add=True, verbose_name="Date d'envoie")),
            ],
        ),
    ]
