# Generated by Django 5.2 on 2025-06-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=40)),
                ('client_phone', models.CharField(max_length=20)),
                ('client_email', models.CharField(max_length=50)),
                ('message_object', models.CharField(max_length=500)),
                ('message', models.TextField()),
                ('type', models.CharField(max_length=500)),
                ('register_date', models.DateField(verbose_name="Date d'envoie")),
            ],
        ),
    ]
