# Generated by Django 5.2 on 2025-06-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=40)),
                ('client_phone', models.CharField(max_length=20)),
                ('client_email', models.CharField(max_length=50)),
                ('message_object', models.CharField(choices=[('simple', 'Simple prise de contact 🤝'), ('date', 'Prise de rendez-vous 📅')], max_length=6)),
                ('message', models.TextField()),
                ('date_reason', models.CharField(choices=[('web', 'Création de site web | application web 🌐'), ('mobile', "Création d'application mobile 📱"), ('hosting', "Mise en ligne d'une application web | mobile 🧱")], max_length=7)),
                ('register_date', models.DateField(auto_now_add=True, verbose_name="Date d'envoie")),
            ],
        ),
    ]
