# Generated by Django 5.2 on 2025-06-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='client_email',
            field=models.CharField(max_length=50, verbose_name='Votre email :'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='client_name',
            field=models.CharField(max_length=40, verbose_name='Votre nom :'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='client_phone',
            field=models.CharField(max_length=20, verbose_name='Votre numéro téléphone :'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='date_reason',
            field=models.CharField(choices=[('web', 'Création de site web | application web 🌐'), ('mobile', "Création d'application mobile 📱"), ('hosting', "Mise en ligne d'une application web | mobile 🧱")], default='simple', max_length=7, verbose_name='Raison du prise de rendez-vous :'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(verbose_name='Votre message :'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message_object',
            field=models.CharField(choices=[('simple', 'Simple prise de contact 🤝'), ('date', 'Prise de rendez-vous 📅')], default='web', max_length=6, verbose_name='Objet du contact :'),
        ),
    ]
