# Generated by Django 5.2 on 2025-06-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message_object',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='type',
            field=models.CharField(max_length=500),
        ),
    ]
